version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  
  express-app:
    build: ./
    container_name: express-app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  
volumes:
  mongo_data: